var cards = [
  'assets/blue-01.png',
  'assets/blue-02.png',
  'assets/blue-03.png',
  'assets/blue-04.png',
  'assets/blue-05.png',
  'assets/blue-06.png',
  'assets/blue-07.png',
  'assets/blue-08.png',
  'assets/blue-09.png',
  'assets/blue-10.png',
  'assets/blue-jack.png',
  'assets/blue-queen.png',
  'assets/blue-king.png',
  'assets/gold-01.png',
  'assets/gold-02.png',
  'assets/gold-03.png',
  'assets/gold-04.png',
  'assets/gold-05.png',
  'assets/gold-06.png',
  'assets/gold-07.png',
  'assets/gold-08.png',
  'assets/gold-09.png',
  'assets/gold-10.png',
  'assets/gold-jack.png',
  'assets/gold-queen.png',
  'assets/gold-king.png',
  'assets/gren-01.png',
  'assets/gren-02.png',
  'assets/gren-03.png',
  'assets/gren-04.png',
  'assets/gren-05.png',
  'assets/gren-06.png',
  'assets/gren-07.png',
  'assets/gren-08.png',
  'assets/gren-09.png',
  'assets/gren-10.png',
  'assets/gren-jack.png',
  'assets/gren-queen.png',
  'assets/gren-king.png',
  'assets/reed-01.png',
  'assets/reed-02.png',
  'assets/reed-03.png',
  'assets/reed-04.png',
  'assets/reed-05.png',
  'assets/reed-06.png',
  'assets/reed-07.png',
  'assets/reed-08.png',
  'assets/reed-09.png',
  'assets/reed-10.png',
  'assets/reed-jack.png',
  'assets/reed-queen.png',
  'assets/reed-king.png',
];
// spade1 {
//   s1
//   html image
// }
// includes
